apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense # if we didn't mention it then it will go into default namespace
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: jagadeesh3373/frontend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          # Limits should be greater than or equal to requests
          limits:
            cpu: 100m
            memory: 128Mi
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80  # service port
    targetPort: 80  # container port